#!/bin/sh

set -e

if test -f .venv/bin/activate
then
    . .venv/bin/activate
fi

if test "$1" = build
then
    #pip install -r requirements.txt
    pip install -e .

elif test "$1" = run
then
    set -a; . .env; set +a
    flask --app mnaccounts.app  run --host 127.0.0.1 --port $SERVER_PORT

elif test "$1" = grun
then
    set -a; . .env; set +a
    gunicorn --config gunicorn.py mnaccounts.app:app

elif test "$1" = docker
then
    set -a; . .env; set +a
    docker container run \
        --name mnaccounts-api-run-1 \
        --rm \
        --env-file .env \
        --hostname `hostname` \
        -p 127.0.0.1:${SERVER_PORT}:${SERVER_PORT} \
        -v `pwd`/..:/opt/src \
        -v `pwd`/../db:/opt/db \
        -ti \
        --entrypoint sh \
        mnaccounts-api
else
    echo "`basename $0` build | run"
    exit 1
fi
