#!/usr/bin/env python3
import os
if 'MNACCOUNT_APP_CONFIG_FILE' not in os.environ:
    os.environ['MNACCOUNT_APP_CONFIG_FILE'] = 'development.config'

import sys
import re

from collections import defaultdict
from datetime import date

from sqlalchemy import or_

import mnaccounts.db

from mnaccounts.model import Base, to_dict
from mnaccounts.model.user import User


def _reset():
    mnaccounts.db.reset()



def test0():
    _reset()

def test1():
    from mnaccounts.model.flaskuser import User
    from mnaccounts.account import bcrypt

    with mnaccounts.db.session() as sess:
        sess.add_all([
            User(
                id=1001,
                login='lina',
                email='lina@example.com',
                hash=bcrypt.generate_password_hash('ZLwebBss9EcLNb2H'),
                apikey='ZLwebBss9EcLNb2H',
                is_authenticated=True,
                is_active=True,
                is_anonymous=False,
            ),
            User(
                id=1002,
                login='yura',
                email='yura@example.com',
                hash=bcrypt.generate_password_hash('yIGWHvGPmCReFkej'),
                apikey='yIGWHvGPmCReFkej',
                is_authenticated=True,
                is_active=True,
                is_anonymous=False,
            ),
            User(
                id=1003,
                login='andriy',
                email='andriy@example.com',
                hash=bcrypt.generate_password_hash('gwLrKaH9ITWrh5sA'),
                apikey='gwLrKaH9ITWrh5sA',
                is_authenticated=True,
                is_active=True,
                is_anonymous=False,
            ),
            User(
                id=1004,
                login='ira',
                email='ira@example.com',
                hash=bcrypt.generate_password_hash('jCCf8zwPKehENtlF'),
                apikey='jCCf8zwPKehENtlF',
                is_authenticated=True,
                is_active=True,
                is_anonymous=False,
            ),
        ])
        sess.commit()



def main():
    mnaccounts.db.init()
    test0()
    #test1()


if __name__ == '__main__':
    sys.exit(main())
